# Default values for karma chart
replicaCount: 1

image:
  repository: ghcr.io/prymitive/karma
  tag: v0.121
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

containerPort: 8080

command:
  - /karma

args:
  - --config.file
  - /etc/config/karma.yml

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

config: |
  alertmanager:
    servers: []

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 100m

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {}
  hosts:
    - host: karma.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - karma.example.com

nodeSelector: {}

tolerations: []

affinity: {}
